### ISSUE TITLE
Add GitHub Actions configuration

### ISSUE THREAD

**Issue by capgadsx** [CsarMan/malla-interactiva#9]
Es posible construir imágenes docker en github utilizando[ GitHub Actions](https://github.com/features/actions).

Lo ideal sería que con cada commit realizado al repositorio se construya una imagen docker (ref #8). Esto se puede automatizar, utilizando GitHub Actions + [DockerHub](https://hub.docker.com).

Actualmente existe una "receta" para lograr esto en el [marketplace de github](https://github.com/marketplace/actions/build-and-push-docker-images).

Esto permitiría integrar el proyecto con los sistemas del LabComp y actualizar [mallas.labcomp.cl](https://mallas.labcomp.cl) de forma automática directamente desde el repositorio.

**Comment by CsarMan** [comment]
Se ha creado el workflow que permite la publicación de la imagen del proyecto aquí 431a806 . [Se puede encontrar aquí](https://hub.docker.com/r/booterman/malla-interactiva)
